/*
 * \file PmsmFoc_SpeedControl.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_SpeedControl.h"
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
//SpeedControl speedControl;
/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
/** @brief Execute the speed PI controller
 *
 * @param SpeedControl Specifies the speed control object.
 *
 * @return speed control output
 * @see Ifx_PicF32_step
 * @ingroup app_speed_control
 */
float32 PmsmFoc_SpeedControl_do(SpeedControl *speedControl)
{
	float32 result;
    if (speedControl->enabled != FALSE)
    {
        result = Ifx_PicF32_step(&speedControl->piSpeed, speedControl->refSpeed - speedControl->measSpeed);
    }
    else
    {
        result = speedControl->piSpeed.uk;
    }
    return result;
}

/** @brief Initialize the speed control object
 *
 * @param SpeedControl Specifies the speed control object.
 *
 * @return None.
 * @see Ifx_PicF32_init
 * @ingroup app_speed_control
 */
void PmsmFoc_SpeedControl_init(SpeedControl *speedControl)
{
	Ifx_PicF32_init(&speedControl->piSpeed);
}
