/*
 * \file PmsmFoc_StateMachine.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_StateMachine.h"

#include "PmsmFoc_UserConfig.h"
#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH

#include "PmsmFoc_CurrentThreeshuntSense.h"
#include "PmsmFoc_PositionAndSpeedAcquisition.h"
#include "PmsmFoc_PwmSvm.h"
#include "PmsmFoc_Interface.h"
#include "TLE9180.h"
#include "IfxCpu.h"
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/

void PmsmFoc_StateMacine_doControlLoop(MotorControl* const motorCtrl)
{
	switch (motorCtrl->controlParameters.state)
	{
	case StateMachine_calibration:

#if(POSITION_SENSOR_TYPE == ENCODER)
		if((motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_notDone) &
				(motorCtrl->positionSensor.encoder.calibrationStatus == Encoder_CalibrationStatus_notDone))
		{
			IfxTLE9180_activateEnable(&tle9180.driver);
		}
		if(motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_notDone)
		{
			PmsmFoc_PhaseCurrentSense_getRawPhaseCurrentValues(&motorCtrl->inverter.phaseCurrentSense);
			PmsmFoc_PhaseCurrentSense_doCalibration(&motorCtrl->inverter.phaseCurrentSense);
		}
		if(motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_done)
		{
			PmsmFoc_doEncoderCalibration(motorCtrl);
		}
		if((motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_done) &
				(motorCtrl->positionSensor.encoder.calibrationStatus == Encoder_CalibrationStatus_done))
		{
			IfxTLE9180_deactivateEnable(&tle9180.driver);
			motorCtrl->controlParameters.state = StateMachine_motorStop;
		}
#else
		if((motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_notDone)
		{
			IfxTLE9180_activateEnable(&tle9180.driver);
		}
		if(motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_notDone)
		{
			PmsmFoc_PhaseCurSense_getRawPhaseCurrentValues(&motorCtrl->inverter.phaseCurrentSense);
			PmsmFoc_PhaseCurrentSense_doCalibration(&motorCtrl->inverter.phaseCurrentSense);
		}
		if((motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_done)
		{
			IfxTLE9180_deactivateEnable(&tle9180.driver);
			motorCtrl->controlParameters.state = StateMachine_motorStop;
		}
#endif
		break;
	case StateMachine_focClosedLoop:
		/* FOC controller. */
		//PmsmFoc_doFieldOrientedControl(motorCtrl);
		/* Update GTM TOM/ATOM duty cycles. */
		//PmsmFoc_doPwmSvmUpdate(&motorCtrl->inverter);
		
		PmsmFoc_ASWCurrentLoop(motorCtrl);
		break;

	case StateMachine_tuneCurrentRegulators:
		PmsmFoc_tuneCurrentRegulator(motorCtrl);
		break;
	case StateMachine_prePositioning:
		break;
	case StateMachine_motorStop:
		/* Current reconstruction */
		PmsmFoc_reconstructCurrent(motorCtrl);

		/* Clarke Transformation */
		PmsmFoc_doClarkeTransform(&motorCtrl->pmsmFoc);

		/* Update electrical position */
		motorCtrl->pmsmFoc.electricalAngle =
				(sint16) PmsmFoc_PositionAcquisition_updatePosition(&motorCtrl->positionSensor);

		/* Park Transformation */
		PmsmFoc_doParkTransform(&motorCtrl->pmsmFoc);
		break;
	case StateMachine_motorIdle:
		/* Current measurement calibration */
		break;
	case StateMachine_vfOpenLoop:
		PmsmFoc_doVfControl(motorCtrl);
		break;
	case StateMachine_enableInverter:
		break;
	default:
		break;
	}
}








