/**
 * \file Arith.FixPoint.Tasking.c
 * \brief Fix-point arithmetics library (Tasking compiler)
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 *
 * $Revision: $1554.1
 * $Date: $2013-06-26 20:12:46 GMT
 */

#ifdef __TASKING__

#include "Arith.FixPoint.Tasking.h"

/** \brief Fix point arithmetics (saturated): r = -a | Q1.15 = Q1.15
 *
 * Perform the operation -a. The result is saturated.
 *
 * \param a Specifies the a parameter
 *
 * \return r = -a
 * \ingroup fixpoint_arithmetics
 */
FixPoint16 __negs_r1Q15_i1Q15(FixPoint16 a)
{
#if 0
// This implementation generates incorrect code when using Tasking 2.5r1. 0xFFFF-a is returned instead
    return -a;
#else
    FixPoint32 Result;
    __asm(
        "   rsubs   %0, %1, #0                      \n"     // %0 = -%1
        : "=d" (Result)
        : "d" (a));
    return (FixPoint16)Result;
#endif
}


/** \brief Fix point arithmetics (saturated): r = abs(a) | Q1.15 = Q1.15
 *
 * Perform the operation abs(a). The result is saturated.
 *
 * \param a Specifies the a parameter
 *
 * \return r = abs(a)
 * \ingroup fixpoint_arithmetics
 */
FixPoint16 __abss_r1Q15_i1Q15(FixPoint16 a)
{
    FixPoint32 Result;

    __asm(
        "   abss.h  %0, %1                      \n"
        : "=d" (Result)
        : "d" (a));
    return (FixPoint16)Result;
}


/** \brief Fix point arithmetics (saturated): r = abs(a) | Q1.31 = Q1.31
 *
 * Perform the operation abs(a). The result is saturated.
 *
 * \param a Specifies the a parameter
 *
 * \return r = abs(a)
 * \ingroup fixpoint_arithmetics
 */
FixPoint32 __abss_r1Q31_i1Q31(FixPoint32 a)
{
    FixPoint32 Result;

    __asm(
        "   abss    %0, %1                      \n"
        : "=d" (Result)
        : "d" (a));
    return Result;
}


/** \brief Fix point arithmetics: r = a / b | Q1.31 = Q1.15 / Q16.0
 *
 * Perform the operation a / b.
 *
 * \param a Specifies the a parameter
 * \param b Specifies the b parameter.
 *
 * \return r = a / b
 * \ingroup fixpoint_arithmetics
 */
FixPoint32 __div_r1Q31_i1Q31_i32I(FixPoint32 a, sint32 b)
{
    FixPoint32 Result;

    __asm(
        "   dvinit  e2, %1, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvadj   e2, e2, %2                      \n"
        "   mov     %0, d2                          \n"
        : "=d" (Result)
        : "d" (a), "d" (b) : "d2", "d3");
    return Result;
}


/** \brief Fix point arithmetics: r = a / b | Q16.16 = Q1.15 / Q1.15
 *
 * Perform the operation a / b.
 *
 * \param a Specifies the a parameter
 * \param b Specifies the b parameter.
 *
 * \return r = a / b
 * \ingroup fixpoint_arithmetics
 */
FixPoint32 __div_r16Q16_i1Q15_i1Q15(FixPoint16 a, FixPoint16 b)
{
    FixPoint32 Result;

    // Qa.b / qc.d = q(32-(b-d)).(b-d)
    __asm(
        "   shas    %2, %2, #-16                    \n"     // Q17.15
        "   dvinit  e2, %1, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvstep  e2, e2, %2                      \n"
        "   dvadj   e2, e2, %2                      \n"
        "   mov     %0, d2                          \n"     // Q16.16
        : "=d" (Result)
        : "d" (a), "d" (b) : "d2", "d3");
    return Result;
}


#endif
