#ifndef OS_COUNTER_CFG_H
# define OS_COUNTER_CFG_H

#include "Std_Types.h"


#define OS_CFG_COUNTER_SW_USED        STD_OFF
#define OS_CFG_COUNTER_PIT_USED       STD_OFF
#define OS_CFG_COUNTER_PFRT_USED      STD_OFF
#define OS_CFG_COUNTER_HRT_USED       STD_ON

#define OS_CFG_NUM_COUNTER_SYSTEMTIMER_CORE0_JOBS     1
#define OS_CFG_NUM_COUNTER_SYSTEMTIMER_CORE1_JOBS     1
#define OS_CFG_NUM_COUNTER_SYSTEMTIMER_CORE2_JOBS     1
#define OS_CFG_NUM_COUNTER_SYSTEMTIMER_CORE3_JOBS     1
#endif