#ifndef OS_HAL_CORE_CFG_H
# define OS_HAL_CORE_CFG_H


#define OS_CFG_NUM_SYSTEM_INTERRUPTSOURCEREFS               9
#define OS_CFG_NUM_CORE_OSCORE0_INTERRUPTSOURCEREFS         0
#define OS_CFG_NUM_CORE_OSCORE1_INTERRUPTSOURCEREFS         0
#define OS_CFG_NUM_CORE_OSCORE2_INTERRUPTSOURCEREFS         0
#define OS_CFG_NUM_CORE_OSCORE3_INTERRUPTSOURCEREFS         0
#endif