#ifndef OS_SCHEDULER_CFG_H
# define OS_SCHEDULER_CFG_H

#include "Std_Types.h"


#define OS_CFG_SCHEDULE_ROUND_ROB_ENABLED        STD_OFF

#define OS_CFG_NUM_TASKQUEUES                    3u

#define OS_CFG_NUM_TASKQUEUE0_OSCORE0_SLOTS      3u
#define OS_CFG_NUM_TASKQUEUE1_OSCORE0_SLOTS      2u
#define OS_CFG_NUM_TASKQUEUE2_OSCORE0_SLOTS      2u

#define OS_CFG_NUM_TASKQUEUE0_OSCORE1_SLOTS      3u
#define OS_CFG_NUM_TASKQUEUE1_OSCORE1_SLOTS      2u
#define OS_CFG_NUM_TASKQUEUE2_OSCORE1_SLOTS      2u

#define OS_CFG_NUM_TASKQUEUE0_OSCORE2_SLOTS      3u
#define OS_CFG_NUM_TASKQUEUE1_OSCORE2_SLOTS      2u
#define OS_CFG_NUM_TASKQUEUE2_OSCORE2_SLOTS      2u

#define OS_CFG_NUM_TASKQUEUE0_OSCORE3_SLOTS      3u
#define OS_CFG_NUM_TASKQUEUE1_OSCORE3_SLOTS      2u
#define OS_CFG_NUM_TASKQUEUE2_OSCORE3_SLOTS      2u
#endif