#ifndef OS_XSIGNAL_CFG_H
# define OS_XSIGNAL_CFG_H

#include "Std_Types.h"


#define OS_CFG_XSIGNAL             STD_ON
#define OS_CFG_XSIG_USEASYNC       STD_OFF


#define OS_CFG_NUM_XSIG_OSCORE0_ISRS                                 1
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE1_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE2_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE3_RECV0_BUFFER    2
#define OS_CFG_NUM_ISR_XSIGANLISR_OSCORE0_PORTS                      3

#define OS_CFG_NUM_XSIG_OSCORE1_ISRS                                 1
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE0_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE2_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE3_RECV0_BUFFER    2
#define OS_CFG_NUM_ISR_XSIGANLISR_OSCORE1_PORTS                      3

#define OS_CFG_NUM_XSIG_OSCORE2_ISRS                                 1
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE1_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE0_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE3_RECV0_BUFFER    2
#define OS_CFG_NUM_ISR_XSIGANLISR_OSCORE2_PORTS                      3

#define OS_CFG_NUM_XSIG_OSCORE3_ISRS                                 1
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE1_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE2_RECV0_BUFFER    2
#define OS_CFG_SIZE_OSCORE0_SEND0_XSIGNALISR_OSCORE0_RECV0_BUFFER    2
#define OS_CFG_NUM_ISR_XSIGANLISR_OSCORE3_PORTS                      3





#endif