/********************************************************************************************************************
 * \file MCMCAN_FD.c
 * \copyright Copyright (C) Infineon Technologies AG 2020
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CANFD.h"
#include "PmsmFoc_Functions.h"
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
mcmcanType                          g_mcmcan;                                   /* Structure for handling MCMCAN     */
volatile uint8                      g_isrRxCount = 0; /* Declared as volatile in order not to be removed by compiler */

float32 ccu_mcanFreq = 40e6;
float32 ccu_mcanFreq_fbk = 0;
uint8 g_isrTxFinished = 0;

IfxCan_Filter g_filterStandardIdConfiguration = { 0, IfxCan_FilterElementConfiguration_storeInRxBuffer, IfxCan_FilterType_dualId, 0x222, 0x222, IfxCan_RxBufferId_0};

/* Function to initialize MCMCAN module and nodes related for this application use case */
void initMcmcan(void)
{
	ccu_mcanFreq_fbk = IfxScuCcu_setMcanFrequency(ccu_mcanFreq);


    IfxCan_Can_initModuleConfig(&g_mcmcan.canConfig, &MODULE_CAN0);
    IfxCan_Can_initModule(&g_mcmcan.canModule, &g_mcmcan.canConfig);
    IfxCan_Can_initNodeConfig(&g_mcmcan.canNodeConfig, &g_mcmcan.canModule);

    const IfxCan_Can_Pins canPins = {
        &IfxCan_TXD00_P20_8_OUT, IfxPort_OutputMode_pushPull,
        &IfxCan_RXD00B_P20_7_IN, IfxPort_InputMode_noPullDevice,
        IfxPort_PadDriver_cmosAutomotiveSpeed4
    };
	g_mcmcan.canNodeConfig.pins = &canPins;

    g_mcmcan.canNodeConfig.busLoopbackEnabled = FALSE;
    g_mcmcan.canNodeConfig.nodeId = IfxCan_NodeId_0;

    g_mcmcan.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;
    g_mcmcan.canNodeConfig.frame.mode = IfxCan_FrameMode_fdLong;

    g_mcmcan.canNodeConfig.txConfig.txMode = IfxCan_TxMode_dedicatedBuffers;
    g_mcmcan.canNodeConfig.txConfig.txBufferDataFieldSize = IfxCan_DataFieldSize_64;

    g_mcmcan.canNodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;
    g_mcmcan.canNodeConfig.interruptConfig.traco.priority = ISR_PRIORITY_CAN_TX;
    g_mcmcan.canNodeConfig.interruptConfig.traco.interruptLine = IfxCan_InterruptLine_5;
    g_mcmcan.canNodeConfig.interruptConfig.traco.typeOfService = IfxSrc_Tos_cpu0;

    IfxCan_Can_initNode(&g_mcmcan.canSrcNode, &g_mcmcan.canNodeConfig);


	
    IfxCan_Can_initNodeConfig(&g_mcmcan.canNodeConfig, &g_mcmcan.canModule);


    g_mcmcan.canNodeConfig.busLoopbackEnabled = FALSE;
    g_mcmcan.canNodeConfig.nodeId = IfxCan_NodeId_0;

    g_mcmcan.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;
    g_mcmcan.canNodeConfig.frame.mode = IfxCan_FrameMode_fdLong;

    //g_mcmcan.canNodeConfig.rxConfig.rxMode = IfxCan_RxMode_fifo0;
    //g_mcmcan.canNodeConfig.rxConfig.rxFifo0DataFieldSize = IfxCan_DataFieldSize_64;
    //g_mcmcan.canNodeConfig.rxConfig.rxFifo0Size = NUMBER_OF_CAN_FD_CASES;
	g_mcmcan.canNodeConfig.rxConfig.rxMode = IfxCan_RxMode_dedicatedBuffers;
    g_mcmcan.canNodeConfig.rxConfig.rxBufferDataFieldSize = IfxCan_DataFieldSize_64;

    g_mcmcan.canNodeConfig.filterConfig.messageIdLength = IfxCan_MessageIdLength_standard;
    g_mcmcan.canNodeConfig.filterConfig.standardListSize = 1;
    g_mcmcan.canNodeConfig.filterConfig.extendedListSize = 0;
    g_mcmcan.canNodeConfig.filterConfig.standardFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_acceptToRxFifo0;
    g_mcmcan.canNodeConfig.filterConfig.extendedFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
    g_mcmcan.canNodeConfig.filterConfig.rejectRemoteFramesWithStandardId = TRUE;
    g_mcmcan.canNodeConfig.filterConfig.rejectRemoteFramesWithExtendedId = TRUE;

    //g_mcmcan.canNodeConfig.interruptConfig.rxFifo0NewMessageEnabled = TRUE;
    //g_mcmcan.canNodeConfig.interruptConfig.rxf0n.priority = ISR_PRIORITY_CAN_RX;
    //g_mcmcan.canNodeConfig.interruptConfig.rxf0n.interruptLine = IfxCan_InterruptLine_4;
    //g_mcmcan.canNodeConfig.interruptConfig.rxf0n.typeOfService = IfxSrc_Tos_cpu0;

    g_mcmcan.canNodeConfig.interruptConfig.messageStoredToDedicatedRxBufferEnabled = TRUE;
    g_mcmcan.canNodeConfig.interruptConfig.reint.priority = ISR_PRIORITY_CAN_RX;
    g_mcmcan.canNodeConfig.interruptConfig.reint.interruptLine = IfxCan_InterruptLine_4;
    g_mcmcan.canNodeConfig.interruptConfig.reint.typeOfService = IfxSrc_Tos_cpu0;

    IfxCan_Can_initNode(&g_mcmcan.canDstNode, &g_mcmcan.canNodeConfig);	
	IfxCan_Can_setStandardFilter(&g_mcmcan.canDstNode, &g_filterStandardIdConfiguration);
	
}

/* Function to initialize both TX and RX messages with the default data values.
 * After initialization of the messages, the TX message will be transmitted.
 */
void transmitCanMessage(void)
{
    IfxCan_Can_initMessage(&g_mcmcan.rxMsg);
    
    //memset((void *)(&g_mcmcan.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_FD_DATA_PAYLOAD);
    memset((void *)(&g_mcmcan.txData[0]), INVALID_TX_DATA_VALUE, MAXIMUM_CAN_FD_DATA_PAYLOAD);

    IfxCan_Can_initMessage(&g_mcmcan.txMsg);

    g_mcmcan.txMsg.messageId = 0x111;
    g_mcmcan.txMsg.messageIdLength = IfxCan_MessageIdLength_standard;
    g_mcmcan.txMsg.frameMode = IfxCan_FrameMode_fdLong;
    g_mcmcan.txMsg.dataLengthCode = IfxCan_DataLengthCode_64;

	//INV
    g_mcmcan.txData[3]  = g_motorpara_transcan.ActSpeed & 0xFF;
	g_mcmcan.txData[2]  = (g_motorpara_transcan.ActSpeed >>  8) & 0xFF;
	g_mcmcan.txData[1]  = (g_motorpara_transcan.ActSpeed >> 16) & 0xFF;
	g_mcmcan.txData[0]  = (g_motorpara_transcan.ActSpeed >> 24) & 0xFF;
	
    g_mcmcan.txData[4]  = (g_motorpara_transcan.DCVoltage >> 24) & 0xFF;
	g_mcmcan.txData[5]  = (g_motorpara_transcan.DCVoltage >> 16) & 0xFF;
	g_mcmcan.txData[6]  = (g_motorpara_transcan.DCVoltage >>  8) & 0xFF;
	g_mcmcan.txData[7]  = g_motorpara_transcan.DCVoltage & 0xFF;
	
    g_mcmcan.txData[11] = g_motorpara_transcan.DutyU & 0xFF;
	g_mcmcan.txData[10] = (g_motorpara_transcan.DutyU >>  8) & 0xFF;
	g_mcmcan.txData[9]  = (g_motorpara_transcan.DutyU >> 16) & 0xFF;
	g_mcmcan.txData[8]  = (g_motorpara_transcan.DutyU >> 24) & 0xFF;
	
    g_mcmcan.txData[15]  = g_motorpara_transcan.DutyV & 0xFF;
	g_mcmcan.txData[14]  = (g_motorpara_transcan.DutyV >>  8) & 0xFF;
	g_mcmcan.txData[13]  = (g_motorpara_transcan.DutyV >> 16) & 0xFF;
	g_mcmcan.txData[12]  = (g_motorpara_transcan.DutyV >> 24) & 0xFF;
	
    g_mcmcan.txData[19]  = g_motorpara_transcan.DutyW & 0xFF;
	g_mcmcan.txData[18]  = (g_motorpara_transcan.DutyW >>  8) & 0xFF;
	g_mcmcan.txData[17]  = (g_motorpara_transcan.DutyW >> 16) & 0xFF;
	g_mcmcan.txData[16]  = (g_motorpara_transcan.DutyW >> 24) & 0xFF;
	
    g_mcmcan.txData[23]  = 0xFF;
	g_mcmcan.txData[22]  = 0xFF;
	g_mcmcan.txData[21]  = (g_motorpara_transcan.ElecAngle) & 0xFF;
	g_mcmcan.txData[20]  = (g_motorpara_transcan.ElecAngle >> 8) & 0xFF;
	
    g_mcmcan.txData[25]  = g_motorpara_transcan.Freq & 0xFF;
	g_mcmcan.txData[24]  = (g_motorpara_transcan.Freq >>  8) & 0xFF;
	
    g_mcmcan.txData[29]  = g_motorpara_transcan.PhaCurrentU & 0xFF;
	g_mcmcan.txData[28]  = (g_motorpara_transcan.PhaCurrentU >>  8) & 0xFF;
	g_mcmcan.txData[27]  = (g_motorpara_transcan.PhaCurrentU >> 16) & 0xFF;
	g_mcmcan.txData[26]  = (g_motorpara_transcan.PhaCurrentU >> 24) & 0xFF;
	
    g_mcmcan.txData[33]  = g_motorpara_transcan.PhaCurrentV & 0xFF;
	g_mcmcan.txData[32]  = (g_motorpara_transcan.PhaCurrentV >>  8) & 0xFF;
	g_mcmcan.txData[31]  = (g_motorpara_transcan.PhaCurrentV >> 16) & 0xFF;
	g_mcmcan.txData[30]  = (g_motorpara_transcan.PhaCurrentV >> 24) & 0xFF;
	
    g_mcmcan.txData[37]  = g_motorpara_transcan.PhaCurrentW & 0xFF;
	g_mcmcan.txData[36]  = (g_motorpara_transcan.PhaCurrentW >>  8) & 0xFF;
	g_mcmcan.txData[35]  = (g_motorpara_transcan.PhaCurrentW >> 16) & 0xFF;
	g_mcmcan.txData[34]  = (g_motorpara_transcan.PhaCurrentW >> 24) & 0xFF;
	
    g_mcmcan.txData[38]  = g_motorpara_transcan.Sector & 0xFF;
	g_mcmcan.txData[39]  = 0xFF;

    /* Send the CAN message with the previously defined TX message configuration and content */
    if(g_isrTxFinished == 0)
	{
		g_isrTxFinished = 1;
		IfxCan_Can_sendMessage(&g_mcmcan.canSrcNode, &g_mcmcan.txMsg, (uint32*)&g_mcmcan.txData[0]);
	}
}
