/*
 * \file PmsmFoc_Interrupts.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_Interrupts.h"
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
/** \brief Interrupt service unit for EVADC, end of EVADC conversion call back
 *
 */

void Os_Isr_CURR_G0CH0()
{
	PmsmFoc_StateMacine_doControlLoop(&g_motorControl);

	//OneEye_osciStep();
}

void Os_Isr_VHVDC_G1CH3()
{
	PmsmFoc_DcLinkVoltageSense_getValue(&g_motorControl.inverter.dcLinkVoltageSense);
}

void Os_Isr_VBEMF_G2CH3()
{
	PmsmFoc_BemfVoltageSense_getValue(&g_motorControl.inverter.bemfVoltageSense);
}

void Os_Isr_Gpt12_Encoder()
{
	IfxGpt12_IncrEnc_onZeroIrq(&g_motorControl.positionSensor.encoder.incrEncoder);
}

void Os_Isr_Qspi_Tlf35584_TxIsr()
{
	IfxCpu_enableInterrupts();
#if (SPI_2_USE_DMA == TRUE)
	IfxQspi_SpiMaster_isrDmaTransmit(&spiMasterQspi2);
#else
	IfxQspi_SpiMaster_isrTransmit(&spiMasterQspi2);
#endif
}

void Os_Isr_Qspi_Tlf35584_RxIsr()
{
	IfxCpu_enableInterrupts();
#if (SPI_2_USE_DMA == TRUE)
	IfxQspi_SpiMaster_isrDmaReceive(&spiMasterQspi2);
#else
	IfxQspi_SpiMaster_isrReceive(&spiMasterQspi2);
#endif
}

void Os_Isr_Qspi_Tlf35584_ErrIsr()
{
	IfxCpu_enableInterrupts();
	IfxQspi_SpiMaster_isrError(&spiMasterQspi2);
}


void Os_Isr_Qspi_Tle9180_TxIsr()
{
	IfxCpu_enableInterrupts();
#if (SPI_4_USE_DMA == TRUE)
	IfxQspi_SpiMaster_isrDmaTransmit(&spiMasterQspi4);
#else
	IfxQspi_SpiMaster_isrTransmit(&spiMasterQspi4);
#endif
}

void Os_Isr_Qspi_Tle9180_RxIsr()
{
	IfxCpu_enableInterrupts();
#if (SPI_4_USE_DMA == TRUE)
	IfxQspi_SpiMaster_isrDmaReceive(&spiMasterQspi4);
#else
	IfxQspi_SpiMaster_isrReceive(&spiMasterQspi4);
#endif
}

void Os_Isr_Qspi_Tle9180_ErrIsr()
{
	IfxCpu_enableInterrupts();
	IfxQspi_SpiMaster_isrError(&spiMasterQspi4);
}
