/**
 * \file TLF35584_Init.c
 * \brief Initialization of TLF35584 ASIC.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between(i) you or the
 * company in which ordinary course of business you are acting and(ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "PmsmFoc_InitTLF35584.h"
#include "Qspi_Init.h"

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
TLF35584 tlf35584;

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

IFX_INLINE void PmsmFoc_Tlf35584_InitSpiChannel(void)
{
	IfxQspi_SpiMaster_ChannelConfig spiChConfig;
    boolean interruptState = IfxCpu_disableInterrupts();
	IfxQspi_SpiMaster_initChannelConfig(&spiChConfig, &TLF35584_SPI);

    /* set the baudrate for this channel */
    spiChConfig.base.baudrate = IFX_TLF35584_BAUDRATE;

    /* set the transfer data width */
    spiChConfig.base.mode.dataWidth = IFX_TLF35584_DATAWIDTH;

    spiChConfig.base.mode.csTrailDelay = 2;
    spiChConfig.base.mode.csInactiveDelay = 2;
    spiChConfig.base.mode.shiftClock = SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge;

    spiChConfig.sls.output.pin    = &TLF35584_SPI_CS_PIN;
    spiChConfig.sls.output.mode   = IfxPort_OutputMode_pushPull;
    spiChConfig.sls.output.driver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    /* initialize channel */
    IfxQspi_SpiMaster_initChannel(&tlf35584.spiChannel, &spiChConfig);

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);
}


/** \brief Initialization for TLF35584
 *
 */

void PmsmFoc_Tlf35584_Init(void)
{
	PmsmFoc_Tlf35584_InitSpiChannel();
	{
		IfxTLF35584_Config tlfConfig;

		tlfConfig.spiChannel= &tlf35584.spiChannel;
		tlfConfig.spiIf.spiGetStatus= (IfxTLF35584_SpiGetStatusIfPtrType)&IfxQspi_SpiMaster_getStatus;
		tlfConfig.spiIf.spiExchange= (IfxTLF35584_SpiExchangeIfPtrType)&IfxQspi_SpiMaster_exchange;
		IfxTLF35584_init(&tlf35584.driver, &tlfConfig);
	}
}

