/**
 * \file TLE9180_Init.h
 * \brief Initialization of TLE9180 ASIC.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between(i) you or the
 * company in which ordinary course of business you are acting and(ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef _TLE9180_INIT_H_
#define _TLE9180_INIT_H_

#include "TLE9180.h"
/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
#define TLE9180_SPI                      spiMasterQspi4           /**< \brief SPI Configurations for TLE9180 Channel */
#define TLE9180_SPI_CS_PIN               IfxQspi4_SLSO3_P22_2_OUT
/******************************************************************************/
/*-------------------------------Data Structures------------------------------*/
/******************************************************************************/
typedef struct
{
	IfxTLE9180                  driver;
	IfxQspi_SpiMaster_Channel   spiChannel;
} TLE9180;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

extern TLE9180 tle9180;

/******************************************************************************/
/*-----------------------------Function Prototypes----------------------------*/
/******************************************************************************/

extern void PmsmFoc_Tle9180_Init(void);
extern void main_Tle9180_test(void);
/** /brief
 *
 * /param
 * /return
 * /note
 * /see
 * /ingroup
 */
IFX_INLINE void PmsmFoc_Tle9180_loadConfiguration(void)
{
    IfxTLE9180_loadStartupConfiguration(&tle9180.driver);
}

#endif /* _TLE9180_INIT_H_ */
