/**
 * \file TLE9180_Init.h
 * \brief Initialization of TLE9180 ASIC.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between(i) you or the
 * company in which ordinary course of business you are acting and(ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "PmsmFoc_InitTLE9180.h"
#include "Qspi_Init.h"
#include "IfxPort_PinMap.h"


#include "PmsmFoc_UserConfig.h"
#include MCUCARD_TYPE_PATH
//#include INVERTERCARD_TYPE_PATH
//#include MOTOR_TYPE_PATH
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
TLE9180 tle9180;

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

IFX_INLINE void PmsmFoc_Tle9180_InitSpiChannel(void)
// Configure SPI Channels for Motor Control Module
{   // Configuration for TLE9180 communication
	/* create channel config */
	IfxQspi_SpiMaster_ChannelConfig spiChConfig;
	IfxQspi_SpiMaster_initChannelConfig(&spiChConfig, &TLE9180_SPI);

	/* set the baudrate for this channel */
	spiChConfig.base.baudrate = IFX_TLE9180_BAUDRATE;

	/* set the transfer data width */
	spiChConfig.base.mode.dataWidth = IFX_TLE9180_DATAWIDTH;

	spiChConfig.base.mode.csTrailDelay = SpiIf_SlsoTiming_1;
	spiChConfig.base.mode.csInactiveDelay = SpiIf_SlsoTiming_7;
	spiChConfig.base.mode.shiftClock = SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge;

	spiChConfig.sls.output.pin    = &TLE9180_SPI_CS_PIN;
	spiChConfig.sls.output.mode   = IfxPort_OutputMode_pushPull;
	spiChConfig.sls.output.driver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

	spiChConfig.channelBasedCs= IfxQspi_SpiMaster_ChannelBasedCs_enabled;

	/* initialize channel */
	IfxQspi_SpiMaster_initChannel(&tle9180.spiChannel, &spiChConfig);
}

/** Tle9180 configuration */
/** \brief Initialization for TLE9180
 *
 */

void PmsmFoc_Tle9180_Init(void)
{
	IfxTLE9180_Config tleConfig;

	PmsmFoc_Tle9180_InitSpiChannel();

	tleConfig.size= 8192;

	tleConfig.pins.enable= TLE9180_ENABLE_PIN;
	tleConfig.pins.error= TLE9180_ERROR_PIN;
	tleConfig.pins.inhibit= TLE9180_INHIBIT_PIN;
	tleConfig.pins.safeOff= TLE9180_SAFEOFF_PIN;

	tleConfig.spiChannel= &tle9180.spiChannel;

	/*Configure the SPI interfaces as QSPI Master Interfaces*/
	tleConfig.spiIf.spiExchange= (IfxTLE9180_SpiExchangeIfPtrType)&IfxQspi_SpiMaster_exchange;     //For TLF9180 only SPI Exchange API is required

	IfxTLE9180_init(&tle9180.driver, &tleConfig);
}

void main_Tle9180_test(void)
{
	tle9180.driver.readIndex = 0;
	IfxTLE9180_readRegister(&tle9180.driver);
}
