/**
 * \file TLF35584_Init.h
 * \brief Initialization of TLF35584 ASIC.

 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between(i) you or the
 * company in which ordinary course of business you are acting and(ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef PMSMFOC_TLF35584_INIT_H_
#define PMSMFOC_TLF35584_INIT_H_

#include "TLF35584.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

#define TLF35584_SPI                           spiMasterQspi2                  /**< \brief SPI Configurations for TLF35584 Channel */
#define TLF35584_SPI_CS_PIN                    IfxQspi2_SLSO1_P14_2_OUT
/******************************************************************************/
/*-------------------------------Data Structures------------------------------*/
/******************************************************************************/
typedef struct
{
	IfxTLF35584                 driver;
	IfxQspi_SpiMaster_Channel   spiChannel;
} TLF35584;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

extern TLF35584 tlf35584;

/******************************************************************************/
/*-----------------------------Function Prototypes----------------------------*/
/******************************************************************************/

extern void PmsmFoc_Tlf35584_Init(void);

#endif /* PMSMFOC_TLF35584_INIT_H_ */
