/**
 * @file Park.c
 * @brief Park transformation.
 * @license
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 *
 * $Revision: 102 $
 * $Date: 2010-06-19 22:41:43 +0200 (Sat, 19 Jun 2010) $
 *
 */

//------------------------------------------------------------------------------
#include "Park.h"

//------------------------------------------------------------------------------
#if !defined(CFG_OPTIMIZE) || (CFG_OPTIMIZE == 0)
/** @brief Park transformation.
 *
 * This function converts the current from the stationary reference frame \f$ (\alpha, \beta) \f$
 * to the rotating reference frame \f$ (d, q) \f$ attached to the rotor flux.
 * @image html "Park.gif"
 *
 * @param mab Specifies the current in the stationary reference frame.
 * @param CosSin Specifies the cosinus and sinus coresponding to the angle \f$ \varphi \f$
 * between the phase U axis and the rotor flux axis.
 *
 * @return Returns the current in the rotating reference frame:
 * \f$
 *   \begin{bmatrix}
 *  i_{sd} \\
 *  i_{sq}
 *  \end{bmatrix}
 *  =
 *  \begin{bmatrix}
 *  \cos \varphi & \sin \varphi \\
 *  -\sin \varphi & \cos \varphi
 *  \end{bmatrix}
 *  *
 *  \begin{bmatrix}
 *  i_{s\alpha} \\
 *  i_{s\beta}
 *  \end{bmatrix}
 * \f$
 *
 * @ingroup motor_control_park
 */
CplxStdReal Park(CplxStdReal *mab, CplxStdReal *cosSin)
{
	CplxStdReal result;
	result.real = __maddms_rSR_iSR_iSR_iSR_iSR(mab->real, cosSin->real, mab->imag, cosSin->imag);
    result.imag = __msubms_rSR_iSR_iSR_iSR_iSR(mab->imag, cosSin->real, mab->real, cosSin->imag);
    return result;
}

/** @brief Reverse Park transformation.
 *
 * This function converts the current from the rotating reference frame \f$ (d, q) \f$
 * to the stationary reference frame \f$ (\alpha, \beta) \f$.
 * @image html "Park.gif"
 *
 * @param mdq Specifies the current in the rotating reference frame.
 * @param CosSin Specifies the cosinus and sinus coresponding to the angle \f$ \varphi \f$
 * between the phase U axis and the rotor flux axis.
 *
 * @return Returns the current in the stationary reference frame:
* \f$
 *  \begin{bmatrix}
 *  i_{s\alpha} \\
 *  i_{s\beta}
 *  \end{bmatrix}
 *  =
 *  \begin{bmatrix}
 *  \cos \varphi & -\sin \varphi \\
 *  \sin \varphi & \cos \varphi
 *  \end{bmatrix}
 *  *
 *  \begin{bmatrix}
 *  i_{sd} \\
 *  i_{sq}
 *  \end{bmatrix}
 * \f$
 * @ingroup motor_control_park
 */
CplxStdReal Park_Reverse(CplxStdReal *mdq, CplxStdReal *cosSin)
{
	CplxStdReal result;
    result.real = __msubms_rSR_iSR_iSR_iSR_iSR(mdq->real, cosSin->real, mdq->imag, cosSin->imag);
	result.imag = __maddms_rSR_iSR_iSR_iSR_iSR(mdq->real, cosSin->imag, mdq->imag, cosSin->real);
    return result;
}
#endif
