/*
 * \file Evadc_Init.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "Evadc_Init.h"
#include "PmsmFoc_UserConfig.h"

#include "PmsmFoc_Inverter.h"

#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH

#if (PHASE_CURRENT_RECONSTRUCTION == USER_LOWSIDE_THREE_SHUNT_WITHOUT_HIGHSIDE_MONITORING)
#include "PmsmFoc_CurrentThreeshuntSense.h"
#include "Evadc_InitCurSenseLsTriShuntWoHsMon.h"
#elif (PHASE_CURRENT_RECONSTRUCTION == USER_LOWSIDE_THREE_SHUNT_WITH_HIGHSIDE_MONITORING)
#include "PmsmFoc_CurrentThreeshuntSense.h"
#include "Evadc_InitCurSenseLsTriShuntHsMon.h"
#elif (PHASE_CURRENT_RECONSTRUCTION == USER_LOWSIDE_SINGLE_SHUNT)
#include "Evadc_InitCurSenseLsSingleShunt.h"
#endif

#if (BEMF_MEASUREMENT == ENABLED)
#include "Evadc_InitVoltageSenseBemf.h"
#endif

#if (DC_LINK_VOLTAGE_MEASUREMENT == ENABLED)
#include "Evadc_InitVoltageSenseDcLink.h"
#endif
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
Adc_Evadc adcEvadc;
/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/
/* First define all the Queue Macros as undefined for groups 0-3 */
#define EVADC_INIT_INIT_GROUP0_QUEUE0(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP0_QUEUE1(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP0_QUEUE2(grpConfig) /* Unused */

#define EVADC_INIT_INIT_GROUP1_QUEUE0(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP1_QUEUE1(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP1_QUEUE2(grpConfig) /* Unused */

#define EVADC_INIT_INIT_GROUP2_QUEUE0(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP2_QUEUE1(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP2_QUEUE2(grpConfig) /* Unused */

#define EVADC_INIT_INIT_GROUP3_QUEUE0(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP3_QUEUE1(grpConfig) /* Unused */
#define EVADC_INIT_INIT_GROUP3_QUEUE2(grpConfig) /* Unused */

#if (PHASE_CURRENT_RECONSTRUCTION == \
     USER_LOWSIDE_THREE_SHUNT_WITHOUT_HIGHSIDE_MONITORING) || \
    (PHASE_CURRENT_RECONSTRUCTION == \
          USER_LOWSIDE_THREE_SHUNT_WITH_HIGHSIDE_MONITORING)
#undef EVADC_INIT_INIT_GROUP0_QUEUE0
#undef EVADC_INIT_INIT_GROUP1_QUEUE0
#undef EVADC_INIT_INIT_GROUP2_QUEUE0
#undef EVADC_INIT_INIT_GROUP3_QUEUE0
#define EVADC_INIT_INIT_GROUP0_QUEUE0(grpConfig) PmsmFoc_Evadc_initGroup0Queue0(grpConfig)
#define EVADC_INIT_INIT_GROUP1_QUEUE0(grpConfig) PmsmFoc_Evadc_initGroup1Queue0(grpConfig)
#define EVADC_INIT_INIT_GROUP2_QUEUE0(grpConfig) PmsmFoc_Evadc_initGroup2Queue0(grpConfig)
#define EVADC_INIT_INIT_GROUP3_QUEUE0(grpConfig) PmsmFoc_Evadc_initGroup3Queue0(grpConfig)
#endif

#if (PHASE_CURRENT_RECONSTRUCTION == USER_LOWSIDE_SINGLE_SHUNT)
#undef EVADC_INIT_INIT_GROUP0_QUEUE0
#undef EVADC_INIT_INIT_GROUP1_QUEUE0
#define EVADC_INIT_INIT_GROUP0_QUEUE0(grpConfig) PmsmFoc_Evadc_initGroup0Queue0(grpConfig)
#define EVADC_INIT_INIT_GROUP1_QUEUE0(grpConfig) PmsmFoc_Evadc_initGroup1Queue0(grpConfig)
#endif

#if (BEMF_MEASUREMENT == ENABLED)
#undef EVADC_INIT_INIT_GROUP1_QUEUE2
#undef EVADC_INIT_INIT_GROUP2_QUEUE2
#undef EVADC_INIT_INIT_GROUP3_QUEUE2
#define EVADC_INIT_INIT_GROUP1_QUEUE2(grpConfig) PmsmFoc_Evadc_initGroup1Queue2(grpConfig)
#define EVADC_INIT_INIT_GROUP2_QUEUE2(grpConfig) PmsmFoc_Evadc_initGroup2Queue2(grpConfig)
#define EVADC_INIT_INIT_GROUP3_QUEUE2(grpConfig) PmsmFoc_Evadc_initGroup3Queue2(grpConfig)
#endif

#if (DC_LINK_VOLTAGE_MEASUREMENT == ENABLED)
#undef EVADC_INIT_INIT_GROUP1_QUEUE1
#undef EVADC_INIT_INIT_GROUP2_QUEUE1
#undef EVADC_INIT_INIT_GROUP3_QUEUE1
#define EVADC_INIT_INIT_GROUP1_QUEUE1(grpConfig) PmsmFoc_Evadc_initGroup1Queue1(grpConfig)
#define EVADC_INIT_INIT_GROUP2_QUEUE1(grpConfig) PmsmFoc_Evadc_initGroup2Queue1(grpConfig)
#define EVADC_INIT_INIT_GROUP3_QUEUE1(grpConfig) PmsmFoc_Evadc_initGroup3Queue1(grpConfig)
#endif

#if (PHASE_CURRENT_RECONSTRUCTION == \
    USER_LOWSIDE_THREE_SHUNT_WITH_HIGHSIDE_MONITORING)
#undef EVADC_INIT_INIT_GROUP2_QUEUE1
#define EVADC_INIT_INIT_GROUP2_QUEUE1(grpConfig) PmsmFoc_Evadc_initGroup2Queue1(grpConfig)
#endif


/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/
IFX_INLINE void PmsmFoc_Evadc_initGroup0(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup1(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup2(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup3(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup4(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup5(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup6(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup7(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup8(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup9(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup10(void);
IFX_INLINE void PmsmFoc_Evadc_initGroup11(void);
IFX_INLINE void PmsmFoc_Evadc_initGroups(void);

/******************************************************************************/
/*----------------------Inline Function Implementations-----------------------*/
/******************************************************************************/

IFX_INLINE void PmsmFoc_Evadc_initModule(void)
{
    /* create configuration */
    IfxEvadc_Adc_Config adcConfig;
    IfxEvadc_Adc_initModuleConfig(&adcConfig, &MODULE_EVADC);
    /* initialize module */
    IfxEvadc_Adc_initModule(&adcEvadc.evadc, &adcConfig);
}

IFX_INLINE void PmsmFoc_Evadc_initGroup0(void)
{
    /* create group configuration*/
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &adcEvadc.evadc);

    adcGroupConfig.groupId= IfxEvadc_GroupId_0;
    adcGroupConfig.master= IfxEvadc_GroupId_0;

    EVADC_INIT_INIT_GROUP0_QUEUE0(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP0_QUEUE1(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP0_QUEUE2(&adcGroupConfig);

    adcGroupConfig.startupCalibration= TRUE;

    IfxEvadc_Adc_initGroup(&adcEvadc.adcGroup0, &adcGroupConfig);
}

IFX_INLINE void PmsmFoc_Evadc_initGroup1(void)
{
    /* create group configuration*/
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &adcEvadc.evadc);

    adcGroupConfig.groupId= IfxEvadc_GroupId_1;
    adcGroupConfig.master= IfxEvadc_GroupId_0;

    EVADC_INIT_INIT_GROUP1_QUEUE0(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP1_QUEUE1(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP1_QUEUE2(&adcGroupConfig);

    adcGroupConfig.startupCalibration= TRUE;

    IfxEvadc_Adc_initGroup(&adcEvadc.adcGroup1, &adcGroupConfig);
}

IFX_INLINE void PmsmFoc_Evadc_initGroup2(void)
{
    /* create group configuration*/
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &adcEvadc.evadc);

    adcGroupConfig.groupId= IfxEvadc_GroupId_2;
    adcGroupConfig.master= IfxEvadc_GroupId_0;

    EVADC_INIT_INIT_GROUP2_QUEUE0(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP2_QUEUE1(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP2_QUEUE2(&adcGroupConfig);

    adcGroupConfig.startupCalibration= TRUE;

    IfxEvadc_Adc_initGroup(&adcEvadc.adcGroup2, &adcGroupConfig);
}

IFX_INLINE void PmsmFoc_Evadc_initGroup3(void)
{
    /* create group configuration*/
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &adcEvadc.evadc);

    adcGroupConfig.groupId= IfxEvadc_GroupId_3;
    adcGroupConfig.master= IfxEvadc_GroupId_0;

    EVADC_INIT_INIT_GROUP3_QUEUE0(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP3_QUEUE1(&adcGroupConfig);
    EVADC_INIT_INIT_GROUP3_QUEUE2(&adcGroupConfig);

    adcGroupConfig.startupCalibration= TRUE;

    IfxEvadc_Adc_initGroup(&adcEvadc.adcGroup3, &adcGroupConfig);
}

IFX_INLINE void PmsmFoc_Evadc_initGroup4(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup5(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup6(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup7(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup8(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup9(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup10(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroup11(void)
{
    /* Not Used */
}

IFX_INLINE void PmsmFoc_Evadc_initGroups(void)
{
    PmsmFoc_Evadc_initGroup0();
    PmsmFoc_Evadc_initGroup1();
    PmsmFoc_Evadc_initGroup2();
    PmsmFoc_Evadc_initGroup3();
    PmsmFoc_Evadc_initGroup4();
    PmsmFoc_Evadc_initGroup5();
    PmsmFoc_Evadc_initGroup6();
    PmsmFoc_Evadc_initGroup7();
    PmsmFoc_Evadc_initGroup8();
    PmsmFoc_Evadc_initGroup9();
    PmsmFoc_Evadc_initGroup10();
    PmsmFoc_Evadc_initGroup11();
}

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
void PmsmFoc_Evadc_initEvadc(Inverter *const inverter)
{
    PmsmFoc_Evadc_initModule();
    PmsmFoc_Evadc_initGroups();

    PmsmFoc_Evadc_initCurrentSenseChannels(inverter);

#if (BEMF_MEASUREMENT == ENABLED)
    PmsmFoc_Evadc_initBemfVoltageSenseChannels(inverter);
#endif

#if (DC_LINK_VOLTAGE_MEASUREMENT == ENABLED)
    PmsmFoc_Evadc_initDcLinkVoltageSenseChannels(inverter);
#endif
}

