/*
 * \file Gpt12_Init.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_Types.h"
#include "IfxGpt12_IncrEnc.h"
#include "Gpt12_Init.h"
#include "PmsmFoc_UserConfig.h"

#include INVERTERCARD_TYPE_PATH
#include MCUCARD_TYPE_PATH
#include MOTOR_TYPE_PATH
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

void PmsmFoc_Gpt12_initGpt12(IfxGpt12_IncrEnc* gpt12IncrEnc)
{
	/* Initialize global clocks */
	IfxGpt12_enableModule(&MODULE_GPT120);
	IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt1BlockPrescaler_8);
	IfxGpt12_setGpt2BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt2BlockPrescaler_4);

	{
		IfxGpt12_IncrEnc_Config gpt12Config;
		IfxGpt12_IncrEnc_initConfig(&gpt12Config, &MODULE_GPT120);

		/* T3 used as position acquisition core */

		/* Configure Sensor */
		gpt12Config.base.offset                    = 0;
		//gpt12Config.base.offset                    = ENCODER_OFFSET;
		gpt12Config.base.reversed                  = ENCODER_REVERSED;
		gpt12Config.base.resolution                = ENCODER_RESOLUTION;
		gpt12Config.base.resolutionFactor          = IfxStdIf_Pos_ResolutionFactor_twoFold;

		/* Configure Speed */
		gpt12Config.base.speedModeThreshold        = ENCODER_SPEED_MODE_THRESHOLD;
		gpt12Config.base.minSpeed                  = ENCODER_BASE_MIN_SPEED;
		gpt12Config.base.maxSpeed                  = ENCODER_BASE_MAX_SPEED;
		gpt12Config.base.speedFilterEnabled 	   = TRUE;
		gpt12Config.base.speedFilerCutOffFrequency = 1000;

		/* Configure Handler */
		gpt12Config.base.updatePeriod              = ENCODER_UPDATE_PERIOD;
		gpt12Config.zeroIsrPriority                = INTERRUPT_PRIORITY_ENCODER_GPT12;
		gpt12Config.zeroIsrProvider                = ENCODER_GPT12_HOST_CPU;

		/* Configure Hardware Resources */
		gpt12Config.pinA                           = ENCODER_GPT12_PIN_A;
		gpt12Config.pinB                           = ENCODER_GPT12_PIN_B;
		gpt12Config.pinZ                           = ENCODER_GPT12_PIN_Z;
		gpt12Config.pinDriver                      = IfxPort_PadDriver_cmosAutomotiveSpeed3;

		IfxGpt12_IncrEnc_init(gpt12IncrEnc, &gpt12Config);
		IfxGpt12_T3_setIncrementalInterfaceInputMode(&MODULE_GPT120, IfxGpt12_IncrementalInterfaceInputMode_bothEdgesTxEUD);
		IfxGpt12_T4_setRemoteControl(&MODULE_GPT120, IfxGpt12_TimerRemoteControl_on);
	}
}

