/*
 * \file Mcu_Init.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Mcu_Init.h"
#include "Qspi_Init.h"
#include "PmsmFoc_InitTLF35584.h"
#include "bsp.h"
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "Qspi_Init.h"
#include "PmsmFoc_InitTLE9180.h"
#include "PmsmFoc_Inverter.h"
#include "PmsmFoc_PositionAndSpeedAcquisition.h"
#include "PmsmFoc_UserConfig.h"
/******************************************************************************/
/*-------------------------------Global variables-----------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Private Variables/Constants--------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
void PmsmFoc_initHardware(MotorControl* const motorCtrl)
{

	IfxCpu_disableInterrupts();

	IfxPort_setPinMode(&MODULE_P13, 0, IfxPort_Mode_outputPushPullGeneral);     /* LED107 */
	IfxPort_setPinHigh(&MODULE_P13, 0);
	IfxPort_setPinMode(&MODULE_P13, 1, IfxPort_Mode_outputPushPullGeneral);     /* LED108 */
	IfxPort_setPinHigh(&MODULE_P13, 1);
	IfxPort_setPinMode(&MODULE_P13, 2, IfxPort_Mode_outputPushPullGeneral);     /* LED109 */
	IfxPort_setPinHigh(&MODULE_P13, 2);
	IfxPort_setPinMode(&MODULE_P13, 3, IfxPort_Mode_outputPushPullGeneral);     /* LED110 */
	IfxPort_setPinHigh(&MODULE_P13, 3);

	/* Initialize SPI interfaces */
	PmsmFoc_Qspi_initQspi();

	{   /* Load power and WDT configurations  */
		IfxCpu_enableInterrupts();            /* Interrupts are required to be enabled for SPI communication */

		/* TLF35584 (Power and WDT ASIC) init */
		PmsmFoc_Tlf35584_Init();        /* This requires connected SPI module Initialized before */
		IfxTLF35584_unprotectRegister();
		IfxTLF35584_disableWindowWatchdog();
		IfxTLF35584_disableErrPinMonitor();
		IfxTLF35584_protectRegister();
		/* Switch TLF to normal state */
		IfxTLF35584_gotoNormalState();

		IfxCpu_disableInterrupts();
	}

	/* Initialize time constants for Time functions, see bsp.c */
	//initTime();

	/* Initialize TLE9180, this requires connected SPI module initialized before */
	//PmsmFoc_Tle9180_Init();

    /* Initialize GTM Driver */
	//PmsmFoc_Gtm_initGtm(&motorCtrl->inverter);

    /* Initialize EVADC Driver */
	//PmsmFoc_Evadc_initEvadc(&motorCtrl->inverter);

	/* Initialize position sensor driver */
	//PmsmFoc_PositionAcquisition_init(&motorCtrl->positionSensor, PositionAcquisition_SensorType_Encoder);

	/* Send startup configuration to TLE9180D */
    //IfxCpu_enableInterrupts();
    //PmsmFoc_Tle9180_loadConfiguration();
    //IfxCpu_disableInterrupts();

}





