/*
 * \file Qspi_Init.c
 * \brief
 * \ingroup
 * \version
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Qspi_Init.h"
#include "PmsmFoc_UserConfig.h"

#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH
/******************************************************************************/
/*-------------------------------Global variables-----------------------------*/
/******************************************************************************/
IfxQspi_SpiMaster           spiMasterQspi2;
IfxQspi_SpiMaster           spiMasterQspi4;

/******************************************************************************/
/*-----------------------------Private Variables/Constants--------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/


/** \brief Initialize QSPI2 Module
 *
 */
IFX_INLINE void PmsmFoc_Qspi_initQspi2(void)
{
	/* create SPI2 module configuration */
	IfxQspi_SpiMaster_Config        spiConfig;
	IfxQspi_SpiMaster_initModuleConfig(&spiConfig, &SPI_2_MODULE);

	/* pin configuration */
	const IfxQspi_SpiMaster_Pins spiPins =
	{
		&SPI_2_CLOCK_PIN,  IfxPort_OutputMode_pushPull,
		&SPI_2_MOSI_PIN,  IfxPort_OutputMode_pushPull,
		&SPI_2_MISO_PIN,  IfxPort_InputMode_pullDown,
		IfxPort_PadDriver_cmosAutomotiveSpeed1
	};
	/* set the maximum baudrate */
	spiConfig.base.maximumBaudrate = 50.0e6;

	/* ISR priorities and interrupt target */
	spiConfig.base.txPriority    = INTERRUPT_PRIORITY_QSPI2_TX;
	spiConfig.base.rxPriority    = INTERRUPT_PRIORITY_QSPI2_RX;
	spiConfig.base.erPriority    = INTERRUPT_PRIORITY_QSPI2_ERR;
	spiConfig.base.isrProvider   = SPI_2_HOST_CPU;
#if (SPI_2_USE_DMA == TRUE)
	spiConfig.dma.txDmaChannelId = SPI_2_TX_DMA_CH;
	spiConfig.dma.rxDmaChannelId = SPI_2_RX_DMA_CH;
	spiConfig.dma.useDma         = TRUE;
#endif
	spiConfig.pins = &spiPins;

	/* initialize module */
	IfxQspi_SpiMaster_initModule(&spiMasterQspi2, &spiConfig);

	{
		volatile Ifx_SRC_SRCR *src = IfxQspi_getErrorSrc(&MODULE_QSPI2);
		IfxSrc_init(src, SPI_2_HOST_CPU, INTERRUPT_PRIORITY_QSPI2_ERR);
		IfxSrc_enable(src);
	}
}

/** \brief Initialize QSPI4 Module
 *
 */
// IFX_INLINE void PmsmFoc_Qspi_initQspi4(void)
// {
	// /* create SPI4 module config */
	// IfxQspi_SpiMaster_Config        spiConfig;
	// IfxQspi_SpiMaster_initModuleConfig(&spiConfig, &SPI_4_MODULE);

	// /* pin configuration */
	// const IfxQspi_SpiMaster_Pins spiPins =
	// {
		// &SPI_4_CLOCK_PIN,  IfxPort_OutputMode_pushPull,
		// &SPI_4_MOSI_PIN,  IfxPort_OutputMode_pushPull,
		// &SPI_4_MISO_PIN,  IfxPort_InputMode_pullDown,
		// IfxPort_PadDriver_cmosAutomotiveSpeed1
	// };

	// /* set the maximum baudrate */
	// spiConfig.base.maximumBaudrate = 50.0e6;

	// /* ISR priorities and interrupt target */
	// spiConfig.base.txPriority    = INTERRUPT_PRIORITY_QSPI4_TX;
	// spiConfig.base.rxPriority    = INTERRUPT_PRIORITY_QSPI4_RX;
	// spiConfig.base.erPriority    = INTERRUPT_PRIORITY_QSPI4_ERR;
	// spiConfig.base.isrProvider   = SPI_4_HOST_CPU;
// #if (SPI_4_USE_DMA == TRUE)
	// spiConfig.dma.txDmaChannelId = SPI_4_TX_DMA_CH;
	// spiConfig.dma.rxDmaChannelId = SPI_4_RX_DMA_CH;
	// spiConfig.dma.useDma         = TRUE;
// #endif
	// spiConfig.pins = &spiPins;

	// /* initialize module */
	// IfxQspi_SpiMaster_initModule(&spiMasterQspi4, &spiConfig);

// //	IfxPort_setPinPadDriver(spiConfig.pins->mrst->pin.port, spiConfig.pins->mrst->pin.pinIndex, spiConfig.pins->pinDriver);

// //	{
// //		volatile Ifx_SRC_SRCR *src = IfxQspi_getErrorSrc(&MODULE_QSPI4);
// //		IfxSrc_init(src, SPI_4_HOST_CPU, INTERRUPT_QSPI4_ERR);
// //		IfxSrc_enable(src);
// //	}
// }



/** \brief Initialize Used SPI Modules
 *
 */
void PmsmFoc_Qspi_initQspi(void)
{
	PmsmFoc_Qspi_initQspi2();
	//PmsmFoc_Qspi_initQspi4();
}






