/*
 * \file Qspi_Init.h
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef QSPI_INIT_H_
#define QSPI_INIT_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "IfxQspi_SpiMaster.h"
#include "IfxDma.h"
#include "PmsmFoc_UserConfig.h"

#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/


#define SPI_2_MODULE                            TLF35584_SPI_MODULE
#define SPI_2_CLOCK_PIN                         TLF35584_SPI_CLOCK_PIN
#define SPI_2_MOSI_PIN                          TLF35584_SPI_MOSI_PIN
#define SPI_2_MISO_PIN                          TLF35584_SPI_MISO_PIN
#define SPI_2_HOST_CPU                          TLF35584_SPI_HOST_CPU
#define SPI_2_USE_DMA                           TLF35584_SPI_USE_DMA
#define SPI_2_TX_DMA_CH                         TLF35584_SPI_TX_DMA_CH
#define SPI_2_RX_DMA_CH                         TLF35584_SPI_RX_DMA_CH


#define SPI_4_MODULE                            TLE9180_SPI_MODULE
#define SPI_4_CLOCK_PIN                         TLE9180_SPI_CLOCK_PIN
#define SPI_4_MOSI_PIN                          TLE9180_SPI_MOSI_PIN
#define SPI_4_MISO_PIN                          TLE9180_SPI_MISO_PIN
#define SPI_4_HOST_CPU                          TLE9180_SPI_HOST_CPU
#define SPI_4_USE_DMA                           TLE9180_SPI_USE_DMA
#define SPI_4_TX_DMA_CH                         TLE9180_SPI_TX_DMA_CH
#define SPI_4_RX_DMA_CH                         TLE9180_SPI_RX_DMA_CH

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
extern IfxQspi_SpiMaster           spiMasterQspi2;
extern IfxQspi_SpiMaster           spiMasterQspi4;

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/
/** /brief
 *
 * /param
 * /return
 * /note
 * /see
 * /ingroup
 */
IFX_EXTERN void PmsmFoc_Qspi_initQspi(void);
/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/



#endif /* QSPI_INIT_H_ */
