/*
 * \file PmsmFoc_Motor.h
 * \brief
 * \ingroup
 * \version 
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


#ifndef PMSMFOC_MOTOR_H_
#define PMSMFOC_MOTOR_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_Types.h"
/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
 typedef struct
{
    boolean	winding;		/**< \brief Winding type: 0 - Wye, 1 - Delta */
    boolean rotorSailency;  /**< \brief Rotor sailency: 0 - Round, 1 - Sailent */
	uint8 polePairs;		/**< \brief Number of pole pairs */
    float32 rs;				/**< \brief Stator resistance per phase in Ohm */
    float32 ms;				/**< \brief Stator mutual inductance in H */
    float32 lm;				/**< \brief Stator inductance fluctuation in H */
    float32 ls;				/**< \brief Stator self-inductance per phase in H */
    float32 l0;				/**< \brief Stator zero-sequence inductance in H */
    float32 ld;				/**< \brief Stator d-axis inductance in H */
    float32 lq;				/**< \brief Stator q-axis inductance in H */
    float32 ldq;			/**< \brief Stator dq-axis inductance in H */
    float32 ke;				/**< \brief Back EMF constant in V.s/rad */
    float32 psiM;			/**< \brief Permanent magnet flux linkage in Wb */
    float32 tc;				/**< \brief Torque constant in N.m/A */
    float32 jm;				/**< \brief Total mechanical inertia in kg.m^2 */
    float32 bm;				/**< \brief Viscous friction coeficient in N.m.s */

    float32	iNom;			/**< \brief Nominal phase current in A */
    float32 iMax;			/**< \brief Maximal phase current in A */
    float32	uNom;			/**< \brief Nominal phase voltage in V */
    float32	pNom;			/**< \brief Nominal power in W */
    float32	pMax;			/**< \brief Maximal power in W */
    float32 nNom;			/**< \brief Nominal speed in rpm */
    float32 nMax;			/**< \brief Maximal speed in rpm */
} MotorParameters;
/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/


#endif /* PMSMFOC_MOTOR_H_ */
