/*
 * \file PmsmFoc_PositionAndSpeedAcquisition.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_PositionAndSpeedAcquisition.h"
#include "Tables.h"

#include "PmsmFoc_UserConfig.h"
#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
Ifx_LowPassPt1F32      lowPassFilter;

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/

void PmsmFoc_PositionAcquisition_init(PositionAcquisition* positionAcquisition, PositionAcquisition_SensorType sensorType)
{

	positionAcquisition->statusOk = TRUE;
    switch(sensorType)
    {
        case PositionAcquisition_SensorType_Hall:
        {
            /* Not implemented*/
            break;
        }
        case PositionAcquisition_SensorType_Encoder:
        {
            PmsmFoc_Gpt12_initGpt12(&positionAcquisition->encoder.incrEncoder);
            break;
        }
        case PositionAcquisition_SensorType_Resolver:
        {
        	/* Not implemented*/
            break;
        }
        case PositionAcquisition_SensorType_Sensorless:
        {
            /* Not implemented*/
            break;
        }
        case PositionAcquisition_SensorType_Encoder_and_Resolver:
        {
        	/* Not implemented*/
            break;
        }
        default:
        {
        	positionAcquisition->statusOk= FALSE;
            break;
        }
    }

    {
    	//positionAcquisition->speedLpf.a = 0.10;
    	//positionAcquisition->speedLpf.b = 0;
    	//positionAcquisition->speedLpf.out = 0;

       // Ifx_LowPassPt1F32_Config lpfConfig;
       // lpfConfig.gain            = 10.0;
       // lpfConfig.cutOffFrequency = 25;
       // lpfConfig.samplingTime    = 50.0e-6;
       // Ifx_LowPassPt1F32_init(&positionAcquisition->speedLpf, &lpfConfig);
    }
}

sint32 PmsmFoc_PositionAcquisition_updatePosition(PositionAcquisition* positionAcquisition)
{
	sint32 position = 0;
	switch(positionAcquisition->sensorType)
	    {
	        case PositionAcquisition_SensorType_Hall:
	        {
	            /* Not implemented*/
	            break;
	        }
	        case PositionAcquisition_SensorType_Encoder:
	        {
	            sint32 rawPosition;
	            IfxGpt12_IncrEnc *encoder= &positionAcquisition->encoder.incrEncoder;

	            IfxGpt12_IncrEnc_update(encoder);
	            rawPosition= IfxGpt12_IncrEnc_getRawPosition(encoder);
	            position= ((rawPosition * (uint32)USER_MOTOR_POLE_PAIR * 0x400U) / encoder->resolution) & 0x3FFU;
	            break;
	        }
	        case PositionAcquisition_SensorType_Resolver:
	        {
	        	/* Not implemented*/
	        	break;
	        }
	        case PositionAcquisition_SensorType_Encoder_and_Resolver:
	        {
	        	/* Not implemented*/
	        	break;
	        }
	        case PositionAcquisition_SensorType_Sensorless:
	        {
	            /* Not implemented*/
	            break;
	        }
	        default: break;
	    }
	    return(position);
}

float32 PmsmFoc_PositionAcquisition_updateSpeed(PositionAcquisition* positionAcquisition)
{
	float32 speed = 0.0f;
	    switch(positionAcquisition->sensorType)
	    {
	        case PositionAcquisition_SensorType_Hall:
	        {
	            /* Not implemented*/
	            break;
	        }
	        case PositionAcquisition_SensorType_Encoder:
	        {
	            speed= IfxGpt12_IncrEnc_getSpeed(&positionAcquisition->encoder.incrEncoder);
	            break;
	        }
	        case PositionAcquisition_SensorType_Resolver:
	        	/* Not implemented*/
	        	break;
	        case PositionAcquisition_SensorType_Encoder_and_Resolver:
	        {
	        	/* Not implemented*/
	        	break;
	        }
	        case PositionAcquisition_SensorType_Sensorless:
	        {
	            /* Not implemented*/
	            break;
	        }
	        default: break;
	    }

	    //speed= Ifx_LowPassPt1F32_do(&positionAcquisition->speedLpf, speed);
	    return(speed);
}
