/*
 * \file test.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_PwmSvm.h"
#include "IfxGtm_Tom_PwmHl.h"
#include "IfxGtm_Trig.h"
#include "IfxStdIf_Timer.h"
#include "PmsmFoc_Inverter.h"
#include "Ifx_Types.h"
#if(EMOTOR_LIB == MC_EMOTOR)
#include "Arith.StdReal.h"
#endif
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
#if(EMOTOR_LIB == MC_EMOTOR)

void PmsmFoc_doSvPwmModulation(Inverter* const inverter, CplxStdReal modulationIndex)
{
	Ifx_TimerValue period;
	period = inverter->pwm3PhaseOutput.pwm.timer->base.period;
	/* Space vector PWM */
	uint8 Sector;
	Sector = SpaceVectorModulation(modulationIndex,period,inverter->pwm3PhaseOutput.pwmOnTimes);
	inverter->pwm3PhaseOutput.adcTrigerPoint= period>>1;
	inverter->pwm3PhaseOutput.sectorSVM = Sector;
}
#endif

void PmsmFoc_doPwmSvmUpdate(Inverter* const inverter)
{
	//iLLD GTM functions
#if(GTM_USED == GTM_ATOM_WITH_DTM_USED )
	//ATOM with DTM
#elif(GTM_USED == GTM_ATOM_WITHOUT_DTM_USED)

#elif(GTM_USED == GTM_TOM_WITHOUT_DTM_USED)

	//TOM without DTM, two Channel per phase
    IfxGtm_Tom_Timer_disableUpdate(&inverter->pwm3PhaseOutput.timer);
    IfxGtm_Tom_Timer_setTrigger(&inverter->pwm3PhaseOutput.timer,
    							inverter->pwm3PhaseOutput.adcTrigerPoint +
								inverter->pwm3PhaseOutput.pwm.base.deadtime + 5);		/*  */
    IfxGtm_Tom_PwmHl_setOnTime(&inverter->pwm3PhaseOutput.pwm, inverter->pwm3PhaseOutput.pwmOnTimes);
    IfxGtm_Tom_Timer_applyUpdate(&inverter->pwm3PhaseOutput.timer);
#endif
}
