/*
 * \file PmsmFoc_CurrentDcLink.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_CurrentDcLinkSense.h"
#include "IfxPort_PinMap.h"

#include "PmsmFoc_UserConfig.h"
#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
#if(INVERTERCARD_TYPE == EMOTOR_DRIVE_V_3_1)

boolean PmsmFoc_CurrentDCLinkSenseHs_init(HighSideCurrentSense *highSideCurrentSense, const HighSideCurrentSense_Config* config)
{
	boolean result = TRUE;

	highSideCurrentSense->input.gain= USER_INVERTER_HS_DCLINK_CUR_SENSE_GAIN;
	highSideCurrentSense->input.offset= USER_INVERTER_HS_DCLINK_CUR_SENSE_OFFSET;
	highSideCurrentSense->input.limits.max= USER_INVERTER_HS_DCLINK_CUR_SENSE_I_MAX;
	highSideCurrentSense->input.limits.min= USER_INVERTER_HS_DCLINK_CUR_SENSE_I_MIN;
	highSideCurrentSense->input.limits.object= NULL_PTR;
	highSideCurrentSense->input.limits.onOutOfRange= NULL_PTR;
	highSideCurrentSense->input.limits.status= PmsmFoc_SensorAdc_LimitsStatus_ok;
	highSideCurrentSense->input.rawvalue= 0U;
	highSideCurrentSense->input.value= 0.0;

	highSideCurrentSense->pins.gainSelelct0 = config->pins.gainSelelct0;
	highSideCurrentSense->pins.gainSelelct1 = config->pins.gainSelelct1;

    IfxPort_setPinMode(highSideCurrentSense->pins.gainSelelct0->port, highSideCurrentSense->pins.gainSelelct0->pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(highSideCurrentSense->pins.gainSelelct1->port, highSideCurrentSense->pins.gainSelelct1->pinIndex, IfxPort_Mode_outputPushPullGeneral);

    return result;
}

void PmsmFoc_CurrentDCLinkSenseHs_doCalibration(HighSideCurrentSense* const highSideCurrentSense)
{

}

void PmsmFoc_CurrentDCLinkSenseHs_setGain(HighSideCurrentSense* const highSideCurrentSense, HighSideCurrentSense_Gain gain)
{


	Ifx_P * portGain0= highSideCurrentSense->pins.gainSelelct0->port;
	uint8 pinIndexGain0= highSideCurrentSense->pins.gainSelelct0->pinIndex;

	Ifx_P * portGain1= highSideCurrentSense->pins.gainSelelct1->port;
	uint8 pinIndexGain1= highSideCurrentSense->pins.gainSelelct1->pinIndex;

	switch(gain)
	{
	case HighSideCurrentSense_Gain_25VperV:
		highSideCurrentSense->selectedGain = 25.0f;
		IfxPort_setPinState(portGain0, pinIndexGain0, IfxPort_State_low);
		IfxPort_setPinState(portGain1, pinIndexGain1, IfxPort_State_low);
		break;
	case HighSideCurrentSense_Gain_50VperV:
		highSideCurrentSense->selectedGain = 50.0f;
		IfxPort_setPinState(portGain0, pinIndexGain0, IfxPort_State_low);
		IfxPort_setPinState(portGain1, pinIndexGain1, IfxPort_State_high);
		break;
	case HighSideCurrentSense_Gain_100VperV:
		highSideCurrentSense->selectedGain = 100.0f;
		IfxPort_setPinState(portGain0, pinIndexGain0, IfxPort_State_high);
		IfxPort_setPinState(portGain1, pinIndexGain1, IfxPort_State_low);
		break;
	case HighSideCurrentSense_Gain_200VperV:
		highSideCurrentSense->selectedGain = 200.0f;
		IfxPort_setPinState(portGain0, pinIndexGain0, IfxPort_State_high);
		IfxPort_setPinState(portGain1, pinIndexGain1, IfxPort_State_high);
		break;
	default:
		highSideCurrentSense->selectedGain = USER_INVERTER_HS_DCLINK_CUR_SENSE_DEFAULT_GAIN;
		IfxPort_setPinState(portGain0, pinIndexGain0, IfxPort_State_low);
		IfxPort_setPinState(portGain1, pinIndexGain1, IfxPort_State_low);
		break;
	}


	highSideCurrentSense->input.gain = ((USER_INVERTER_MAX_ADC_VDD_V/(4096 * highSideCurrentSense->selectedGain * USER_INVERTER_DC_HIGH_SIDE_SHUNT_OHM)));


}

void PmsmFoc_CurrentDCLinkSenseHs_resetCalibrationStatus(HighSideCurrentSense* const highSideCurrentSense)
{
	HighSideCurrentSense_Config hsCurrentConfig;

	hsCurrentConfig.pins.gainSelelct0 = INA225AIDGK_GS0;
	hsCurrentConfig.pins.gainSelelct1 = INA225AIDGK_GS1;

	PmsmFoc_CurrentDCLinkSenseHs_init(highSideCurrentSense, &hsCurrentConfig);
	highSideCurrentSense->calibration.status= PmsmFoc_SensorAdc_CalibrationStatus_notDone;
}

PmsmFoc_SensorAdc_CalibrationStatus PmsmFoc_CurrentDCLinkSenseHs_getCalibrationStatus(HighSideCurrentSense* const highSideCurrentSense)
{
	return highSideCurrentSense->calibration.status;
}

float32 PmsmFoc_CurrentDCLinkSenseHs_limitsExecute(PmsmFoc_SensorAdc_Limits* limits, float32 in)
{
    if (in > limits->max)
    {
        limits->status = PmsmFoc_SensorAdc_LimitsStatus_max;
        if(limits->onOutOfRange != NULL_PTR)
        {
        	limits->onOutOfRange(limits->object, limits->status,limits->info);
        }
    }
    else if (in < limits->min)
    {
        limits->status = PmsmFoc_SensorAdc_LimitsStatus_min;
        if(limits->onOutOfRange != NULL_PTR)
        {
            limits->onOutOfRange(limits->object, limits->status,limits->info);
        }
    }
    else
    {
        limits->status = PmsmFoc_SensorAdc_LimitsStatus_ok;
    }
    return in;
}

float32 PmsmFoc_CurrentDCLinkSenseHs_updateAnalogInput(PmsmFoc_SensorAdc* const highSideCurrentSenseCh)
{
    float32 value = 1.0f;
    uint32 rawValue = 1;

    rawValue = IfxEvadc_Adc_getResult(&highSideCurrentSenseCh->adcChannel).B.RESULT;

    /* Scale Input */
    value = (rawValue * highSideCurrentSenseCh->gain + highSideCurrentSenseCh->offset);

    /* Check limits */
    value = PmsmFoc_CurrentDCLinkSenseHs_limitsExecute(&highSideCurrentSenseCh->limits, value);
    /* Store value */
    highSideCurrentSenseCh->rawvalue = rawValue;
    highSideCurrentSenseCh->value = value;
    return value;
}

void PmsmFoc_CurrentDCLinkSenseHs_getRawCurrentValue(HighSideCurrentSense* const highSideCurrentSense)
{
	PmsmFoc_CurrentDCLinkSenseHs_updateAnalogInput(&highSideCurrentSense->input);
}


#endif
