/*
 * \file PmsmFoc_Macro.h
 * \brief
 * \ingroup pmsm_foc_configuration
 * \version
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _PMSM_FOC_MACRO_H_
#define _PMSM_FOC_MACRO_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/

/** \brief Hardware kit. Refer to the header file description above */
#define KIT_A2G_TC387_MOTORCTRL                 				(1U)
#define CUSTOM_KIT                            					(2U)

/** \brief Controller Card. Refer to the header file description above */
#define APP_KIT_TFT_TC387A										(1U)
#define CUSTOM_MCU                            					(2U)

/** \brief Inverter Card. Refer to the header file description above */
#define EMOTOR_DRIVE_V_3_1										(1U)
#define CUSTOM_INVERTER											(2U)

/** \brief Motor Type. Refer to the header file description above  */
#define NANOTEC_MOTOR_DB42S02                  					(1U)
#define NANOTEC_MOTOR_DB42S03                  					(2U)
#define CUSTOM_MOTOR                           					(3U)
#define	MAXON_EC_MAX30											(4U)
#define QBL4208													(5U)

/** \brief Current Sensing Feedback Scheme */
#define USER_LOWSIDE_SINGLE_SHUNT                            	(1U)
#define USER_LOWSIDE_THREE_SHUNT_WITHOUT_HIGHSIDE_MONITORING 	(2U)
#define USER_LOWSIDE_THREE_SHUNT_WITH_HIGHSIDE_MONITORING    	(3U)
#define USER_HIGHSIDE_SINGLE_SHUNT                           	(4U)

/** \brief FOC Control Scheme  */
#define SPEED_CONTROL											(1U)
#define CURRENT_CONTROL					    					(2U)

/** \brief Position Sensor Type  */
#define ENCODER						        					(1U)
#define RESOLVER						        				(2U)
#define HALL							        				(3U)
#define SENSORLESS						        				(4U)
#define xGMR													(5U)

/** \brief Used GTM Configuration  */
#define GTM_TOM_WITHOUT_DTM_USED								(1U)
#define GTM_ATOM_WITHOUT_DTM_USED								(2U)
#define GTM_ATOM_WITH_DTM_USED									(3U)

#define ENABLED                                 				(1U)
#define DISABLED                                				(0U)

/** \brief Motor Control Library	*/
#define MC_EMOTOR												(1U)
#define CUSTOM													(2U)

/* Motor Winding Connection */
#define DELTA													(0U)
#define WYE														(1U)

/* PMSM Types */
#define SPMSM													(0U)
#define IPMSM													(1U)

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/




#endif /* _PMSM_FOC_MACRO_H_ */
